<?php
/* LiangLee Theme Designer
 * FrameWork for Liang Lee Plugins
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @package LiangLeeFramework
 * @subpackage LiangLee Theme Designer
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File bodyandsrch.php
 */

?>
<table border="0">
  <tr>
    <td><div class='elgg-module-inline'>
      <div class='elgg-head'>
        <h3><?php echo elgg_echo('leethemed:body'); ?></h3>
      </div>
    </div>
        <hr/>
        <p> <?php echo elgg_echo('leethemed:body:clr'); ?> </p>
      <p>
          <?php 
/*
* Regiser Settings for Header color
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_body_bgcolor]", 
"placeholder" => "#fff",
"id" => "bodyc",
"value" => $vars['entity']->Leethemed_body_bgcolor)); ?>
        </p>
      </p>
        </p>
        <hr/>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <div class='elgg-module-inline'>
        <br />
        <br />
        <br />
        <div class='elgg-head'>
          <h3><?php echo elgg_echo('leethemed:search') ?></h3>
        </div>
      <div>
        <p> <?php echo elgg_echo('leethemed:search:clr'); ?></p>
      <p>&nbsp;</p>
      <p>
          <?php /*
* Regiser Settings for Search bar border color
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_search_br]", 
"placeholder" => "#fff",
"id" => "srchc",
"value" => $vars['entity']->Leethemed_search_br)); ?>
        </p>
      <p></p>
      <hr/>
        <br />
        <br />
        <div class='elgg-module-inline'>
        <br />
        <br />
        <div class='elgg-head'>
          <h3><?php echo elgg_echo('leethemed:logo'); ?></h3>
        </div>
      <hr/>
        <br />
        <?php echo elgg_echo('leethemed:logo:url'); ?> <br />
        <?php 
/*
* Regiser Settings Header Logo
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_logo]", 
"placeholder" => "http://localhost/logo.jpg",
"value" => $vars['entity']->Leethemed_logo));
?>
        </p>
        </p>
        </p>
        <p>&nbsp; </p></td>
  </tr>
</table>
