<?php
/* LiangLee Theme Designer
 * FrameWork for Liang Lee Plugins
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @package LiangLeeFramework
 * @subpackage LiangLee Theme Designer
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File header.php
 */

?>
<table border="\&quot;0\&quot;">
  <tr>
    <td width="301"><div class='elgg-module-inline'>
        <div class='elgg-head'>
          <h3><?php echo elgg_echo('leethemed:logo:header') ?></h3>
        </div>
      <hr/>
        <p> <?php echo elgg_echo('leethemed:logo:header:img:clr');?> <br />
            <?php /*
* Regiser Settings for Header imgage or color
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_header_bgorimg]", 
"placeholder" => "color",
"value" => $vars['entity']->Leethemed_header_bgorimg)); ?>
        </p>
      <p>
          <?php 
echo elgg_echo('leethemed:logo:header:img'); ?>
          <br />
          <?php 
/*
* Regiser Settings for Header imgage
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_header_bgimg]", 
"placeholder" => "http://localhost/bg.jpg",
"value" => $vars['entity']->Leethemed_header_bgimg));
?>
        </p>
      <p>
        <?php 
echo elgg_echo('leethemed:logo:header:height');?>
          <br />
          <?php 
echo elgg_view("input/text", array(
"name" => "params[Leethemed_header_height]", 
"placeholder" => "100px",
"value" => $vars['entity']->Leethemed_header_height)); ?>
        </p>
      <p> <?php echo elgg_echo('leethemed:logo:header:clr'); ?> <br />
        </p>
      <div class="form-item">
          <?php
/*
* Regiser Settings for body Bg color
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_header_bgcolor]", 
"placeholder" => "#ffffff",
"id" => "color",
"value" => $vars['entity']->Leethemed_header_bgcolor));
?>
        </div>
      <hr/>
      &nbsp;
      </p></td>
  </tr>
</table>
