<?php
/* LiangLee Theme Designer
 * FrameWork for Liang Lee Plugins
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @package LiangLeeFramework
 * @subpackage LiangLee Theme Designer
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File tbar.php
 */

?>
<table border="0">
  <tr>
    <td><div class='elgg-module-inline'>
        <div class='elgg-head'>
          <h3><?php echo elgg_echo('leethemed:topbar'); ?></h3>
        </div>
      <div>
        <hr/>
        <p> <?php echo elgg_echo('leethemed:logo:header:img:clr'); ?> <br />
            <?php
/*
* Regiser Settings topbar bg color
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_tbar_bgorcolor]", 
"placeholder" => "image",
"value" => $vars['entity']->Leethemed_tbar_bgorcolor));	 ?>
        </p>
      <p> <?php echo elgg_echo('leethemed:topbar:bgurl'); ?> <br />
            <?php
/*
* Regiser Settings topbar bg image
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_background]", 
"placeholder" => "http://www.yourwebsite.com/background_topbar.jpg",
"value" => $vars['entity']->Leethemed_background));	?>
        </p>
      <p> <?php echo elgg_echo('leethemed:topbar:clr'); ?> <br />
            <?php 
/*
* Regiser Settings for topbar color
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_tbar_bgcolor]", 
"placeholder" => "#ffffff",
"id" => "tbarc",
"value" => $vars['entity']->Leethemed_tbar_bgcolor));	?>
        </p>
      <p> <?php echo elgg_echo('leethemed:topbar:height');?> <br />
            <?php
/*
* Regiser Settings for Header imgage
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_tbar_height]", 
"placeholder" => "34",
"value" => $vars['entity']->Leethemed_tbar_height));	 ?>
        </p>
      <hr/></td>
  </tr>
</table>
