<?php
/* LiangLee Theme Designer
 * FrameWork for Liang Lee Plugins
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @package LiangLeeFramework
 * @subpackage LiangLee Theme Designer
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File walledg.php
 */

?>
<table border="0">
  <tr>
    <td><div class='elgg-module-inline'>
        <div class='elgg-head'>
          <h3><?php echo elgg_echo('leethemed:walledg'); ?></h3>
        </div>
      <div>
        <hr/>
        <p> <?php echo elgg_echo('leethemed:logo:header:img:clr'); ?> <br />
            <?php
/*
* Regiser Settings walledg bg color
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_walledg_bgorcolor]", 
"placeholder" => "image",
"value" => $vars['entity']->Leethemed_walledg_bgorcolor));	 ?>
        </p>
      <p> <?php echo elgg_echo('leethemed:walledg:bgurl'); ?> <br />
            <?php
/*
* Regiser Settings walledg bg image
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_walledg_background]", 
"placeholder" => "http://www.yourwebsite.com/background_walledg.jpg",
"value" => $vars['entity']->Leethemed_walledg_background));	?>
        </p>
      <p> <?php echo elgg_echo('leethemed:walledg:clr'); ?> <br />
            <?php 
/*
* Regiser Settings for walled garden color
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_walledg_bgcolor]", 
"placeholder" => "#ffffff",
"id" => "walledgc",
"value" => $vars['entity']->Leethemed_walledg_bgcolor));	?>
        </p>
      <hr/>
	  </td>
  </tr>
</table>
