<?php
/* LiangLeeThemeDesigner
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Framework
 * @subpackage LiangLeeThemeDesigner
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File start.php
 */
 
elgg_register_event_handler('init', 'system', 'LiangLeeThemeDesigner');

/*
 * Register Plugin Settings
 *
 * @access admin
 */
function LiangLeeThemeDesigner() {
/*
 * Add A ColorPicker Css To Admin
 *
 * @access Public
 */
elgg_extend_view('css/admin', 'LiangLeeThemeDesigner/css/css');
/*
 * Register a Logo Enable Disable Function
 *
 * @access admin
 */
elgg_register_plugin_hook_handler("register", "all", 'LiangLeeThemeDesigner_logo');


/*
 * Register Error if Framework is missing and Pluing is Enabled
 *
 * @access admin
 */
if (!elgg_is_active_plugin('LiangleeFramework')) {
 if (elgg_is_admin_logged_in()) {
 /*
 * Register Error to Admin if framework is missing.
 *
 * @access admin
 */
 register_error(elgg_echo('lianglee:framewrok:miss'));
 } else {
/*
 * Register Error to Users in Code if framework is missing.
 *
 * @access public
 */ 
 register_error(elgg_echo('lianglee:framewrok:miss:code'));	
     }
    }  
}
/*
 *  Register a Logo Enable Disable Function.
 *
 * @access public
 */ 
function LiangLeeThemeDesigner_logo(){
if (elgg_get_plugin_setting("Leethemed_logotop", "LiangLeeThemeDesigner") == 'disable') {
/*
 * Unregister Topbar Logo.
 *
 * @access public
 */
        elgg_unregister_menu_item('topbar', 'elgg_logo');
   }
}