<?php
/* LiangLee Theme Designer
 * FrameWork for Liang Lee Plugins
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @package LiangLeeFramework
 * @subpackage LiangLee Theme Designer
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File bodyandsrch.php
 */

?>
<table border="0">
  <tr>
    <td width="360"><div class='elgg-module-inline'>
      <div class='elgg-head'>
        <h3><?php echo elgg_echo('leethemed:clrl:body'); ?></h3>
      </div>
      <br />
    </div>
        <p> </p>
      <p><?php echo elgg_echo('leethemed:clrl:note'); ?></p>
      <br />
        <?php echo LiangLee_view('LiangLeeThemeDesigner','colors/header');  ?>
      </p>
        <br />
        <br />
        <div class='elgg-module-inline'>
          <div class='elgg-head'>
            <h3><?php echo elgg_echo('leethemed:clrl:srch'); ?></h3>
          </div>
          <br />
        </div>
      <p><?php echo elgg_echo('leethemed:clrl:note'); ?><br />
            <?php echo LiangLee_view('LiangLeeThemeDesigner','colors/srch');  ?></p></td>
  </tr>
</table>
