<?php
/* LiangLee Theme Designer
 * FrameWork for Liang Lee Plugins
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @package LiangLeeFramework
 * @subpackage LiangLee Theme Designer
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File topbar.php
 */

?>
<table border="0">
  <tr>
    <td width="360"><div class='elgg-module-inline'>
      <div class='elgg-head'>
        <h3><?php echo elgg_echo('leethemed:clrl:walledg'); ?></h3>
      </div>
      <br />
    </div>
        <hr/>
        <p><?php echo elgg_echo('leethemed:clrl:note'); ?></p>
      <p><?php echo LiangLee_view('LiangLeeThemeDesigner','colors/walledg');  ?></p>
      <hr/></td>
  </tr>
</table>
