<?php
/* LiangLee Theme Designer
 * FrameWork for Liang Lee Plugins
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @package LiangLeeFramework
 * @subpackage LiangLee Theme Designer
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File settings.php
 */
/**
* Get Veersion
**/
$plug_ver = LiangLee_version('LiangLeeThemeDesigner');
$plug_rel = LiangLee_release('LiangLeeThemeDesigner');
/**
* Add Farbtastic javascript
**/
LiangLee_inc_js('LiangLeeThemeDesigner','jquery/farbtastic.js');
/*
* Regiser Settings for topbar logo
*/

echo elgg_echo('leethemed:logo:1:0');
echo "<br />\n";
echo elgg_view('input/dropdown', array(
    'name' => 'params[Leethemed_logotop]',
    'value' => $vars['entity']->liang_lee_zh,
    'options_values' => array(
	'Enable' => 'Enable Topbar Logo', 
	'disable' => 'Disable TopBar Logo'
	)));
			
echo "<hr/>\n"; 
echo "      <table border=\"0\">\n"; 
echo "        <tr>\n"; 
echo "          <td width=\"301\"><h2>\n";

echo elgg_echo('leethemed:logo:header');
echo "<hr/></h2>\n"; 
echo "            <p>\n";
echo elgg_echo('leethemed:logo:header:img:clr');
echo "<br />\n";
/*
* Regiser Settings for Header imgage or color
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_header_bgorimg]", 
"placeholder" => "color",
"value" => $vars['entity']->Leethemed_header_bgorimg));

echo "           </p>\n"; 
echo "            <p>\n";

echo elgg_echo('leethemed:logo:header:img');
echo "<br />\n";
/*
* Regiser Settings for Header imgage
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_header_bgimg]", 
"placeholder" => "http://localhost/bg.jpg",
"value" => $vars['entity']->Leethemed_header_bgimg));

echo "           </p>\n"; 
echo "            <p>\n";
echo elgg_echo('leethemed:logo:header:clr');
echo "<br />\n";
/*
* Regiser Settings for body Bg color
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_header_bgcolor]", 
"placeholder" => "#ffffff",
"value" => $vars['entity']->Leethemed_header_bgcolor));

echo "           </p>\n"; 
echo "            <p>\n";
echo "<hr/>&nbsp;</p></td>\n"; 
echo "          <td width=\"53\">&nbsp;&nbsp;&nbsp;</td>\n"; 
echo "          <td width=\"452\"><h2>\n";
 echo elgg_echo('leethemed:clrl');
echo "<br />\n";
echo "      </h2>\n"; 
echo "            <hr/>\n"; 
echo "            <p>\n";
echo elgg_echo('leethemed:clr:gen'); echo "</p>\n"; 
echo "            <p>\n";
LiangLee_view('LiangLeeThemeDesigner','colors/get');echo "      </p>\n"; 
echo "            <hr/></td>\n"; 
echo "        </tr>\n"; 
echo "        <tr>\n"; 
echo "          <td>&nbsp;</td>\n"; 
echo "          <td>&nbsp;</td>\n"; 
echo "          <td>&nbsp;</td>\n"; 
echo "        </tr>\n"; 
echo "        <tr>\n"; 
echo "          <td><h2><strong>\n";
echo elgg_echo('leethemed:body'); echo "</strong>\n"; 
echo "</h2>\n"; 
echo "<hr/>\n"; 
echo "\n"; 
echo "<p>\n";
echo elgg_echo('leethemed:body:clr'); echo "</p>\n"; 
echo "<p>\n"; 
/*
* Regiser Settings for Header color
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_body_bgcolor]", 
"placeholder" => "#fff",
"value" => $vars['entity']->Leethemed_body_bgcolor));
echo "     </p>\n"; 
echo "              </p>\n"; 
echo "            </p>\n"; 
echo "            <hr/><h2><strong>\n";
echo elgg_echo('leethemed:search'); echo "<hr/></strong></h2>\n"; 
echo "            <p>\n";
echo elgg_echo('leethemed:search:clr'); echo "</p>\n"; 
echo "            <p>&nbsp;</p>\n"; 
echo "            <p>\n";
/*
* Regiser Settings for Search bar border color
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_search_br]", 
"placeholder" => "#fff",
"value" => $vars['entity']->Leethemed_search_br));
echo "  </p>\n"; 
echo "<p><hr/>\n"; 
echo " <h2><strong>\n";
echo elgg_echo('leethemed:logo'); echo "</strong></h2>\n"; 
echo "            <hr/>\n"; 
echo "<br />\n";
echo elgg_echo('leethemed:logo:url'); echo "<br />\n";
/*
* Regiser Settings Header Logo
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_logo]", 
"placeholder" => "http://localhost/logo.jpg",
"value" => $vars['entity']->Leethemed_logo));
echo "      </p>\n"; 
echo "              </p>            \n"; 
echo "              </p>\n"; 
echo "\n"; 
echo "            <p>&nbsp; </p></td>\n"; 
echo "          <td>&nbsp;</td>\n"; 
echo "          <td><h2><strong>\n";
echo elgg_echo('leethemed:topbar'); echo "<br />\n"; 
echo "          </strong></h2>\n"; 
echo "            <hr/>\n"; 
echo "            <p>\n";
echo elgg_echo('leethemed:logo:header:img:clr'); echo "<br />\n";
/*
* Regiser Settings topbar bg color
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_tbar_bgorcolor]", 
"placeholder" => "image",
"value" => $vars['entity']->Leethemed_tbar_bgorcolor));	
echo "</p>\n"; 
echo "          <p>\n";
echo elgg_echo('leethemed:topbar:bgurl'); echo "<br />\n";
/*
* Regiser Settings topbar bg image
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_background]", 
"placeholder" => "http://www.yourwebsite.com/background_topbar.jpg",
"value" => $vars['entity']->Leethemed_background));	
echo "          </p>\n"; 
echo "          <p>\n";
echo elgg_echo('leethemed:topbar:clr'); echo "<br />\n";
/*
* Regiser Settings for topbar color
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_tbar_bgcolor]", 
"placeholder" => "#ffffff",
"value" => $vars['entity']->Leethemed_tbar_bgcolor));	
echo "          </p>\n"; 
echo "          <p>\n";
echo elgg_echo('leethemed:topbar:height'); echo "<br />\n";
/*
* Regiser Settings for Header imgage
*/
echo elgg_view("input/text", array(
"name" => "params[Leethemed_tbar_height]", 
"placeholder" => "34",
"value" => $vars['entity']->Leethemed_tbar_height));	
echo "       </p>\n"; 
echo "          <hr/></td>\n"; 
echo "        </tr>\n"; 
echo "</table>\n"; 
echo "      <hr/>\n";
echo "      <p>\n";
/*
* Add Version
*/
echo "Version: \n";
echo $plug_ver; 
echo "</p>\n";
echo "      <p>\n";
/*
* Add release
*/
echo " Release: \n";
echo $plug_rel; 
echo " </p>\n";
/*
* Add copyright
*/
echo elgg_echo('lianglee:copyr:12'); 
echo "<br />\n";
?>

	  
